name: main

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    defaults:
     run:
      shell: cmd
    
    steps:
    - name: Download
      run: |
        c:
        cd "C:\Users\Public\Desktop\"
        git clone https://github.com/odin-lang/Odin
        dir
        cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build>"
        vcvarsall.bat x64
        cd "C:\Users\Public\Desktop\Odin"
        dir
