name: main

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    defaults:
     run:
      shell: cmd
    
    steps:
    - name: Download
      run: |
        c:
        cd "C:\Users\Public\Desktop\"
        git clone https://github.com/odin-lang/Odin
        dir
