name: main

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    defaults:
     run:
      shell: cmd
    
    steps:
    - name: Download
      run: |
        c:
        cd "C:\Users\Public\Desktop\"
        git clone https://github.com/odin-lang/Odin
        git clone https://github.com/zkxjzmswkwl/odin-injector.git
        dir
    - name: Test
      run: |
         c:
         cd "C:\Users\Public\Desktop\Odin"
         build.bat
    - name: run
      run: |
         c:
         cd "C:\Users\Public\Desktop\odin-injector"
         dir
         cd odin-injector
         ../Odin/odin.exe build .
         dir
